# Dicionário
# Estrutura, chave e valor
# Símbolo {}

# notas = {}  # Dicionário vazio
# notas['Matemática'] = 8.5
# notas['Portugues'] = 7.0
# notas['História'] = 9.2
# notas['Biologia'] = 9.9
# del notas['Biologia']
# print(notas)

# Cadastro em Dicionários

# livros = {}
# lista_cadastros = []

# for i in range(3):
#     titulo = input('Informe o título: ')
#     autor = input('Informe o autor: ')
#     ano = int(input('Informe o ano: '))
#     genero = input('Informe o gênero: ')

#     livros = {
#         'Título' : titulo, 
#         'Autor' : autor,
#         'Ano' : ano,
#         'Gênero' : genero
#     }

#     lista_cadastros.append(livros)
#     print(f'Livro {i + 1} Cadastrado.')